# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ordinal_bart_main <- function(y, x, xtest, burn, nd, m, nc, pbd, pb, alpha, betap, kappa, Ad, s, inc_root, dstarbar) {
    .Call('_OrderedBart_ordinal_bart_main', PACKAGE = 'OrderedBart', y, x, xtest, burn, nd, m, nc, pbd, pb, alpha, betap, kappa, Ad, s, inc_root, dstarbar)
}

